---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/accounts":
    get:
      summary: list accounts
      responses:
        '200':
          description: successful
    post:
      summary: create account
      responses:
        '200':
          description: successful
    parameters:
      - name: parent_id
        in: path
        description: parent_id
        required: true
  
      - name: name
        in: path
        description: name
        required: true
        schema:
          type: string
  "/accounts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show account
      responses:
        '200':
          description: successful
    patch:
      summary: update account
      responses:
        '200':
          description: successful
    put:
      summary: update account
      responses:
        '200':
          description: successful
    delete:
      summary: delete account
      responses:
        '200':
          description: successful
  "/all_parents":
    parameters:
      - name: user_id
        in: path
        description: add 'all_parents?user_id=id'
        required: true
    get:
      summary: all_parents account
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
